defaults:
  - data: image_folder
  - model: dcam_eae
  - trainer: default
  - _self_

project_name: dcam_pytorch
seed: 42
checkpoint_path: null
compile_model: false
output_dir: ${hydra:run.dir}
wandb:
  enabled: true
  project: DCAM
  entity: null
  name: null
  tags: []
  mode: online
